name: CI/CD Pipeline

# Trigger on pushes to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test
        run: |
          mvn clean install    # Compiles and packages the application
          mvn test             # Runs tests


  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run if the "build" job succeeds

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy
      - name: Deploy application
        run: echo "Deploying application..."