name: CI/CD Pipeline

# Trigger on pushes to the main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test
        run: mvn clean install -X

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run if the "build" job succeeds

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deployment step (replace with your actual deployment command)
      - name: Deploy application
        run: echo "Deploying application..."
